### ISSUE TITLE
ace.js files should be in a separate package

### ISSUE THREAD

**Issue by ppvk** [rmsmith/ace.dart#54]
I am in a position where the ace version contained in this package has a bug, fixed in the latest release of ace. I wish to use the newer version and can successfully implement it within the ace.dart wrapper.

However, when I build my application, the included ace distribution in ace.dart is also distributed with my finished application, even though I do not require it. This forces me to delete the packages/ace directory every build.

A solution would be to package the required js files as their own pub package, and instruct users to add it to their pubspec.yaml if they need it. In my particular case, I could just not include that 'ace-js' package, and use my more recent version.

**Comment by rmsmith** [comment]
Are you building your application with `pub build` or with a custom build script?  I'm guessing the former as with a custom script you'd have full control to exclude files.

I would be okay with removing the included js files, as it would simplify the maintenance of this package; also the `ace-builds` seem to be happening less frequently now as compared to previously, so it might be better to leave the js inclusion up to the user (they could either pull in the new pub package or manually include ace themselves).

I don't have the bandwidth myself to publish / maintain a new package, is that something you would be willing to take on?  I suppose we would need it as at least a `dev dependency` of this package for the sake of the examples and tests.

**Comment by rmsmith** [comment]
Another idea is to just hoist the `js` files out of `lib` and to the top-level of this package, and to pull them into the examples and tests using relative urls instead of package urls.  This could be done without needing a new package.  A new package could then be published by any interested party who is willing to maintain it.

**Comment by rmsmith** [comment]
Sorry for the spam, but `pub build` really should allow for excluding files like most (all?) other build systems, which would solve this issue for you without requiring any breaking changes to others who use the included js.  I found this dart issue to track:

https://code.google.com/p/dart/issues/detail?id=16645

In that issue it is said this can be done today with some transformer magic perhaps.

**Comment by ppvk** [comment]
I had considered a transformer, but figured adding another moving part wasn't a good solution when the source of my problem was having too much of something (the JS files). I do realize this would be a breaking change, and if it's too much to ask I'll probably end up going with the transformer solution.

I am attracted to your second comment however, and seems like it would simplify things for myself and, like you stated earlier, the package maintainer. I expect the users to find it not too difficult to download ace and include it in their web/js or more appropriate directory. 

In fact, I would think those who are writing an application for a single purpose wouldn't even use the majority of ace, since the unused language and theme files wouldn't need to be distributed. For example, In my case I only need SVG syntax highlighting.

I have several solutions available for my particular needs, but if there are more single purpose projects like mine that depend on this package, having them provide their own files may be a welcome change.

**Comment by rmsmith** [comment]
Okay I've just merged in a pull request that hoists the javascript files out of `lib/`; the tests are passing and the examples build so it looks to be good.  If you could test out the changes before I publish that would be much appreciated.

**Comment by ppvk** [comment]
I'll check it out and get back to you.

**Comment by ppvk** [comment]
It works as expected within my SVG editing application, however when I run `ace_test.html` in dartium test 279 (`testLineHeight`) fails. Running the test in Firefox when compiled to js passes just fine. I'm not sure if this is problematic or not. It seems possible that Dartium may some inherent styling that overrides the line-height, or the newer ace.js build has changed line height on their end. Do you remember if this was the case before?

**Comment by rmsmith** [comment]
Thanks for trying it out in your application; I've gone ahead and published version 0.6.0+24.2.15 so I'm closing this issue.  

Regarding `testLineHeight` that is strange (it passes for me in Dartium on Windows) but it isn't a great test case.  I've committed a change that makes it more forgiving (compares >= instead of > the fontSize) so that may fix it for you.

**Comment by ppvk** [comment]
I can confirm that your latest commit has fixed the failed test. Thanks a bunch. :)
