### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by sergeykaul** [rmsmith/ace.dart#57]
Hi Ross,
I can't install Ace (Fedora 20, Dart Editor (build 42828)).
Steps to reproduce:
create new project, open pubspec, add Ace and run 'pub get'.
result:
Run Tools > Pub Get to install packages
Pub get failed, [1] Resolving dependencies...
The null object does not have a getter 'isNotEmpty'.

NoSuchMethodError: method not found: 'isNotEmpty'
Receiver: null
Arguments: []
dart:core                                                                                                                                Object.noSuchMethod
package:path/src/style/posix.dart 34                                                                                                     PosixStyle.rootLength
package:path/src/internal_style.dart 46                                                                                                  InternalStyle.getRoot
package:path/src/parsed_path.dart 47                                                                                                     ParsedPath.ParsedPath.parse
package:path/src/context.dart 529                                                                                                        Context._parse
package:path/src/context.dart 108                                                                                                        Context.dirname
package:path/path.dart 145                                                                                                               dirname
/mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/source/path.dart 105                 PathSource.parseDescription
/mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/pubspec.dart 522                     Pubspec._parseDependencies.<fn>.<fn>
/mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/pubspec.dart 577                     Pubspec._wrapFormatException
/mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/pubspec.dart 516                     Pubspec._parseDependencies.<fn>
dart:collection                                                                                                                          Object&MapMixin.forEach
/mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/pubspec.dart 467                     Pubspec._parseDependencies
/mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/pubspec.dart 113                     Pubspec.devDependencies
/mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/pubspec.dart 104                     Pubspec.dependencies
/mnt/data/b/build/slave/dart-editor-linux-stable/build/dart/sdk/lib/_internal/pub_generated/lib/src/solver/backtracking_solver.dart 514  Traverser._traversePackage.<fn>
dart:isolate                                                                                                                             _RawReceivePortImpl._handleMessage
This is an unexpected error. Please run

    pub --trace 'get'

and include the results in a bug report on http://dartbug.com/new.
------------------------------------------------------------
Other packages are installed correctly, so I decided to inform you before report on http://dartbug.com/new

**Comment by rmsmith** [comment]
Hi Sergey,

This looks like a generic `pub` error, as the message indicates it is an "unexpected error".  I think that I have seen this myself a week or so ago (I may have done `pub cache repair` to fix it, but my memory is unclear).  I see that you've opened a general `dartbug` for this, I think that is the right thing to do :)  thanks!

https://code.google.com/p/dart/issues/detail?id=22717

**Comment by sergeykaul** [comment]
Hi Ross, 
Thank you for quick answer. I tried pub cache repair but this did not help me :-(

**Comment by rmsmith** [comment]
I'm going to close this out since the `dartbug` says that this is fixed, which is consistent with what I've seen in the 1.9 dev branch.  When I saw this error it must have gone away when I upgraded my dev SDK to a version with the fix, so you'll probably need to switch to the dev branch or wait for the upcoming 1.9 stable release in order to get the fix.
