### ISSUE TITLE
Multiple instances of ace crashes Chrome

### ISSUE THREAD

**Issue by pisabev** [rmsmith/ace.dart#58]
I'm having problem with multiple instances. It's seems that the triger point is 50. I'm not sure that the problem is in this library or in ace.js itself though. It works in Firefox. It seems that the session.mode parameter is doing something as it doesn't crash with no session.mode.

import 'dart:html';
import 'package:ace/ace.dart' as ace;
import 'package:ace/proxy.dart';

main() {

    var editors = [];
    for(int i = 0; i < 50; i++) {
        ace.implementation = ACE_PROXY_IMPLEMENTATION;
        editors.add(ace.edit(new DivElement())
            ..session.mode = new ace.Mode.named('html'));
    }

}

Edited:
After further investigation it seems that the problem is with Ace and workers. If I set .session.useWorker = false, it works ok.

**Comment by rmsmith** [comment]
It does sound like you are running into a resource limitation such as out-of-memory perhaps.  This is likely unrelated to the Dart layer, other than the fact that the Dart wrappers add some additional memory usage.

Having  >50 editors is probably not advised unless you have a very specific use case.  More likely you'd want to re-use editors and swap the EditSession or Document.

**Comment by pisabev** [comment]
Hi,
The problem with that many editors is because it's a single page app and there is no refresh. I'm not using 50 editors at once but on ocasions(in popup window) and without refresh they seems to "stay"/leak in the memory. Now I use it with session.useWorker=false and it's ok. You are right, the problem is not in ace.dart, it's in ace.js and chrome.

**Comment by rmsmith** [comment]
I will close this issue then if there is nothing specific to the dart layer going on.  If you do find anything specific to the dart code feel free to re-open the issue with more details, thanks.
